
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class Proporcao extends javax.swing.JFrame {    
    double erro=0.0;//e    
    double nivelC=0.0;//Z    
    double popu=0.0;//N    
    double porcent=0.0;//p
    double result=0.0;//n
    
    public Proporcao() {
        initComponents();
        rdb68.setSelected(true);
        nivelC=1.0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdb68 = new javax.swing.JRadioButton();
        rdb90 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        rdb955 = new javax.swing.JRadioButton();
        rdb99 = new javax.swing.JRadioButton();
        rdb95 = new javax.swing.JRadioButton();
        rdb997 = new javax.swing.JRadioButton();
        lblResult = new javax.swing.JLabel();
        txtPopulacao = new javax.swing.JTextField();
        txtPorcentagem = new javax.swing.JTextField();
        txtErro = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnQuestao1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnMedia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(2147483647, 2147483647));

        rdb68.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdb68.setText("68%");
        rdb68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb68ActionPerformed(evt);
            }
        });

        rdb90.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdb90.setText("90%");
        rdb90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb90ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CÁLCULO AMOSTRAL");
        jLabel1.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("População");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Heterogeneidade (%)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Margem de erro (%)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nível de confiança");

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        rdb955.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdb955.setText("95,5%");
        rdb955.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb955ActionPerformed(evt);
            }
        });

        rdb99.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdb99.setText("99%");
        rdb99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb99ActionPerformed(evt);
            }
        });

        rdb95.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdb95.setText("95%");
        rdb95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb95ActionPerformed(evt);
            }
        });

        rdb997.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdb997.setText("99,7%");
        rdb997.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb997ActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblResult.setText("0.0");

        txtPopulacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPopulacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPopulacaoKeyTyped(evt);
            }
        });

        txtPorcentagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPorcentagem.setText("50");
        txtPorcentagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPorcentagemKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcentagemKeyTyped(evt);
            }
        });

        txtErro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtErro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtErroKeyTyped(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnQuestao1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuestao1.setText("?");
        btnQuestao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestao1ActionPerformed(evt);
            }
        });

        btnMedia.setText("Estimativa de Média");
        btnMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMedia))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPopulacao, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                        .addComponent(txtErro)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdb90)
                                            .addGap(18, 18, 18)
                                            .addComponent(rdb99))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdb68)
                                            .addGap(18, 18, 18)
                                            .addComponent(rdb955))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdb95)
                                            .addGap(18, 18, 18)
                                            .addComponent(rdb997))))
                                .addComponent(btnLimpar)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPorcentagem))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCalcular)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblResult)))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuestao1))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuestao1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtErro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rdb68)
                    .addComponent(rdb955))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdb99)
                    .addComponent(rdb90))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdb95)
                    .addComponent(rdb997))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(lblResult))
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if(txtErro.getText().equals("")||(txtPorcentagem.getText().equals("")&&txtPorcentagem.getText().equals("0"))){
            JOptionPane.showMessageDialog(null, "Certifique de preencher os campos!","AVISO",JOptionPane.WARNING_MESSAGE);
        }
        else{
            if(txtPopulacao.getText().equals("")||txtPopulacao.getText().equals("0"))
                popu=0.0;
            else
                popu=Double.parseDouble(txtPopulacao.getText());
            
            erro=Double.parseDouble(txtErro.getText());
            erro=erro/100.0;            
            porcent=Double.parseDouble(txtPorcentagem.getText());
            porcent=porcent/100.0;

            if(popu==0.0){
                //infinita
                try{
                    result=(nivelC*nivelC*porcent*(1-porcent))/(erro*erro);
                    lblResult.setText(result+" = "+Math.ceil(result));
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Ocorreu algum erro!","AVISO",JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                //finita
                //System.out.print("popu "+popu+"\nnivelC "+nivelC+"\nporcent "+porcent+"\nerro "+erro);
                try{
                    result=(popu*nivelC*nivelC*porcent*(1-porcent))/((popu-1)*erro*erro+nivelC*nivelC*porcent*(1-porcent));
                    lblResult.setText(result+" = "+Math.ceil(result));
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Ocorreu algum erro!","AVISO",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void rdb68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb68ActionPerformed
        if (rdb68.isSelected()) {
            rdb90.setSelected(false);
            rdb95.setSelected(false);
            rdb955.setSelected(false);
            rdb99.setSelected(false);
            rdb997.setSelected(false);
            
            nivelC=1.0;
        }
    }//GEN-LAST:event_rdb68ActionPerformed

    private void rdb90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb90ActionPerformed
        if (rdb90.isSelected()) {
            rdb68.setSelected(false);
            rdb95.setSelected(false);
            rdb955.setSelected(false);
            rdb99.setSelected(false);
            rdb997.setSelected(false);
            
            nivelC=1.645;
        }
    }//GEN-LAST:event_rdb90ActionPerformed

    private void rdb95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb95ActionPerformed
        if (rdb95.isSelected()) {
            rdb90.setSelected(false);
            rdb68.setSelected(false);
            rdb955.setSelected(false);
            rdb99.setSelected(false);
            rdb997.setSelected(false);
            
            nivelC=1.96;
        }
    }//GEN-LAST:event_rdb95ActionPerformed

    private void rdb955ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb955ActionPerformed
        if (rdb955.isSelected()) {
            rdb90.setSelected(false);
            rdb95.setSelected(false);
            rdb68.setSelected(false);
            rdb99.setSelected(false);
            rdb997.setSelected(false);
            
            nivelC=2.0;
        }
    }//GEN-LAST:event_rdb955ActionPerformed

    private void rdb99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb99ActionPerformed
        if (rdb99.isSelected()) {
            rdb90.setSelected(false);
            rdb95.setSelected(false);
            rdb955.setSelected(false);
            rdb68.setSelected(false);
            rdb997.setSelected(false);
            
            nivelC=2.575;
        }
    }//GEN-LAST:event_rdb99ActionPerformed

    private void rdb997ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb997ActionPerformed
        if (rdb997.isSelected()) {
            rdb90.setSelected(false);
            rdb95.setSelected(false);
            rdb955.setSelected(false);
            rdb99.setSelected(false);
            rdb68.setSelected(false);
            
            nivelC=3.0;
        }
    }//GEN-LAST:event_rdb997ActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        rdb68.setSelected(true);
        nivelC=1.0;
        txtPopulacao.setText("");
        txtErro.setText("");
        txtPorcentagem.setText("50");
        lblResult.setText("0.0");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtPopulacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPopulacaoKeyTyped
        char c = evt.getKeyChar();
        
        if((c == ',')){
            evt.setKeyChar('.');
        }
        else if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == '.'))) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Esse campo aceita somente números!","INVÁLIDO",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtPopulacaoKeyTyped

    private void txtErroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtErroKeyTyped
        char c = evt.getKeyChar();
        
        if((c == ',')){
            evt.setKeyChar('.');
        }
        else if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == '.'))) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Esse campo aceita somente números!","INVÁLIDO",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtErroKeyTyped

    private void txtPorcentagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentagemKeyTyped
        char c = evt.getKeyChar();
        
        if((c == ',')){
            evt.setKeyChar('.');
        }
        else if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_ENTER) ||(c == '.'))) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Esse campo aceita somente números!","INVÁLIDO",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtPorcentagemKeyTyped

    private void btnQuestao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestao1ActionPerformed
        JOptionPane.showMessageDialog(null, "Se a população não é conhecida, devemos considerá-la como infinita, assim, "
                + "\nbasta deixar o campo como \"0\" ou vazio que o cálculo será realizado.","População",JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_btnQuestao1ActionPerformed

    private void txtPorcentagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentagemKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            java.awt.event.ActionEvent evt2=null;
            btnCalcularActionPerformed(evt2);
        }
    }//GEN-LAST:event_txtPorcentagemKeyPressed

    private void btnMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaActionPerformed
        new MediaAmostra().setVisible(true);
    }//GEN-LAST:event_btnMediaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proporcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proporcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proporcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proporcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proporcao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMedia;
    private javax.swing.JButton btnQuestao1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JRadioButton rdb68;
    private javax.swing.JRadioButton rdb90;
    private javax.swing.JRadioButton rdb95;
    private javax.swing.JRadioButton rdb955;
    private javax.swing.JRadioButton rdb99;
    private javax.swing.JRadioButton rdb997;
    private javax.swing.JTextField txtErro;
    private javax.swing.JTextField txtPopulacao;
    private javax.swing.JTextField txtPorcentagem;
    // End of variables declaration//GEN-END:variables
}
